###########################################################################################
# This is a YML file. Be careful when editing. Check your edits in a YAML checker like    #
# the one at http://yaml-online-parser.appspot.com                                        #
###########################################################################################
# This is a configuration file for SkyBlock core.
# For other configurations, please take a look in the plugin folder for:
# - worlds.yml | schematics/configuration.yml | challenges.yml
---

## Do not change this
version: 2

## Game Prefix.
Prefix: "§l§cＭＲ§fＦＡＣＥ &e"
## Allow debugging
debug: true
## Allow to get Updates from GitHub database
allowUpdate: false
## Locale language
##  Locales are CASE_SENSITIVE!
##  Available locales are:
##    en_US - English by larryTheCoder.
##    de_DE - German by UnexMC
defaultlanguage: "en_US"

# Database
## You should NEVER change this in during mid-game.
database:
  # Configuration of DATABASE Connection:
  #  SQLITE - custom sqlite file
  #  MYSQL  - custom MySql configuration
  connection: sqlite
  prefix: ""
  SQLite:
    # SQLite file name.
    # You can pick any name or include a directory path
    # for this config.
    file-name: "database.db"
  MySQL:
    # Fully implemented, syncs and low latency connection
    host: localhost
    port: 3306
    username: "root"
    password: ""
    database: "ASkyBlock"

# Economy functionality
economy:
  # Enable EconomyAPI integration?
  # You can set this to 'true' if you has an Economy plugin listed below
  # If there is no economy plugin detected, this functionality will be disabled.
  #  Supported economy are:
  #  - EconomyAPI
  enable: false
  # Starting island money,
  # You can decide if the island should be paid or not.
  payNewIsland: false
  # Island cost $$$
  #  You do NOT have to put a '$' symbol
  islandCost: 10

##### Island Related Settings #####
island:
  # Island name limit
  #   Here you can control the
  #   limit of the island naming size
  #   you can also set this to -1 so the size will be infinite
  nameLimit: 20
  # The island chunks set, block set per tick.
  #   Here, you can control how much blocks will be removed per
  #   tick, the higher value is set, the much higher CPU usage will be used.
  chunkResetPerBlocks: 128
  # Delays island creation after the player has created/removed their island.
  #    You can configure this option if you do not want players to create islands in such
  #    of a ridiculous amount of time. The values are in MINUTES.
  island-delay-timeout: 180
  # Restricted commands in Island / SkyBlock
  #   level. You must respect the command format
  #   Such as `/example1, /example2`
  # (Unavailable)
  restrictedCommands: "/exampleCommand, /exampleCommand2"
  # The island default gamemode during teleportation
  gamemode: 0
  # Island addMember time out
  #   You can use -1 for unlimited time but
  #   Recommended 20 seconds
  timeOut: 20
  # Load player islands from the cache that are active within x days
  #   This is config helps you to clears out useless
  #   inactive players caches from memory.
  cache-load-before: 30
  # Items section
  items:
    # Items that will be in the chest when the player starts an island
    # Must be in Nukkit Item format. Format is <ID>:<Qty> or <ID>:<Data>:<Qty>
    # Use <Data> to set the durability of a item or to select sub-items/colors.
    #
    # To use this, please set `USE_CONFIG_CHEST` to true on the schematic
    # configuration to use this properly.
    #
    # Check console for errors and guidance after reloading configuration
    chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 325:1:10 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'

# Protection settings
# Some features may not be available to set.
protection:
  # Protection Setting Flags:
  # ACID_DAMAGE, ANVIL, BEACON, BED, BREAK_BLOCKS, BREEDING, BREWING,
  # BUCKET, COLLECT_LAVA, COLLECT_WATER, CHEST, CRAFTING, CROP_TRAMPLE,
  # DOOR, EGGS, ENCHANTING, ENDER_PEARL, ENTER_EXIT_MESSAGES, FIRE, FIRE_EXTINGUISH,
  # FIRE_SPREAD, FURNACE, GATE, HURT_MOBS, LEASH, LEVER_BUTTON, PLACE_BLOCKS,
  # PRESSURE_PLATE, PVP, MILKING, SPAWN_EGGS, SHEARING, VILLAGER_TRADING,
  # VISITOR_ITEM_DROP, VISITOR_ITEM_PICKUP
  #
  # -- World defaults --
  # Applies everywhere and are the default for islands and spawn.
  # If not listed, default is false.
  world:
    # Acid causes damage above sea-level (if acid is active)
    ACID_DAMAGE: true
    # Allow anvil use
    ANVIL: false
    # Allow beacon use
    BEACON: false
    # Allow bed use
    BED: false
    # Players can break blocks or generally damage things
    BREAK_BLOCKS: false
    # Allow animal breeding
    BREEDING: false
    # Allow use of cauldrons and brewing stands
    BREWING: false
    # Allow use of buckets, either fill or dump them
    BUCKET: false
    # Collect Lava (overrides BUCKET setting for collecting lava)
    COLLECT_LAVA: false
    # Collect water (overrides BUCKET setting for collecting water)
    COLLECT_WATER: false
    # Allow access chests of any kind, droppers, dispensers and hoppers
    CHEST: false
    # Allow use of crafting benches
    CRAFTING: true
    # Allow creepers to hurt players (but not damage blocks)
    CREEPER_PAIN: true
    # Allow crop trampling
    CROP_TRAMPLE: false
    # Allow use of doors or trapdoors. Not including redstone activations.
    DOOR: true
    # Allow chicken egg throwing
    EGGS: false
    # Allow use of enchanting tables
    ENCHANTING: true
    # Allow enderpearl throwing
    ENDER_PEARL: false
    # Enable or disable join/leave messages from the player's island
    ENTER_EXIT_MESSAGES: true
    # Allow fire (flint & steel use, TNT priming) Making portals is allowed.
    FIRE: false
    # Can extinguish fires by punching them
    FIRE_EXTINGUISH: false
    # Allow fire spreading
    FIRE_SPREAD: false
    # Allow furnace use
    FURNACE: true
    # Allow gate use
    GATE: false
    # Allow friendly mob hurting(cows etc.)
    HURT_MOBS: false
    # Allow monsters hurting
    HURT_MONSTERS: true
    # Allow leash use
    LEASH: false
    # Allow lever or button use
    LEVER_BUTTON: true
    # Cows can be milked
    MILKING: true
    # Allow monsters to spawn naturally
    MONSTER_SPAWN: true
    # Players can place blocks
    PLACE_BLOCKS: false
    # Allow pressure plate activation by players
    PRESSURE_PLATE: true
    # Allow PVP in the overworld
    PVP: false
    # Spawn eggs can be used
    SPAWN_EGGS: false
    # Allow sheep shearing
    SHEARING: false
    # Allow trading with villagers
    VILLAGER_TRADING: true
    # Allow item drop
    VISITOR_ITEM_DROP: true
    # Allow item pickup
    VISITOR_ITEM_PICKUP: true
  # -- Island Settings --
  # Settings for islands. Some are for visitors, some for the island itself.
  # If setting is not listed, it will not show in GUI and the world default will be used.
  # Add settings here to give the player the ability to see them in the GUI. Give the
  # player the permission for the setting for them to be able to change the setting.
  island:
    # Allow visitor anvil use
    ANVIL: true
    # Allow visitor beacon use
    BEACON: false
    # Allow visitor bed use
    BED: false
    # Allow visitor block breaking, or other damage
    BREAK_BLOCKS: false
    # Allow visitor animal breeding
    BREEDING: false
    # Allow visitor use of cauldrons and brewing stands
    BREWING: false
    # Allow visitor access chests of any kind, droppers, dispensers and hoppers
    CHEST: false
    # Allow visitors to use crafting benches
    CRAFTING: true
    # Allow visitor use of doors or trapdoors. Not including redstone activations.
    DOOR: true
    # Allow visitor chicken egg throwing
    EGGS: false
    # Allow visitors to use enchanting tables
    ENCHANTING: true
    # Allow visitor furnace use
    FURNACE: true
    # Allow gate use
    GATE: true
    # Allow pressure plate activation by visitors (players only)
    PRESSURE_PLATE: false
    # Allow visitors to shear sheep
    SHEARING: false

# General section
general:
  # The time required for the player to get teleported to their
  #  island destination, you can set this to 0 if you want this to be
  #  disabled.
  islandTeleportDelay: 2
  # Teleport cancel distance
  #  How far can a player travel until the teleportation stops
  #  You can't disable this but you can specify a higher values of this
  #  so that the distance that the player travels wont be cancelled.
  teleportCancelDistance: 0.2
  # Broadcast 1st time challenge completion messages to all players.
  #  Change to false if the spam becomes too much.
  broadcastmessages: false
  # The magic cobble stone generator
  #  This generator relies on the island level, the higher player's island
  #  level, the more chances that the custom ores will generate [As configured below]
  #  The generation of this blocks are fluent and consistence.
  usemagiccobblegen: true
  # This keys wont even be bothered if "usemagiccobblegen" were set to false.
  #  And if its not, then you can continue modifying this settings so that the
  #  the probabilities of a block being set is used for generating custom blocks.
  magiccobblegenchances:
    # These probabilities will apply by default
    default:
      COBBLESTONE: 75.0
      STONE: 10.0
      COAL_ORE: 7.5
      IRON_ORE: 5.0
      DIAMOND_ORE: 2.0
      EMERALD_ORE: 0.5
    # These probabilities will apply if island level is higher than 500.
    # Must have "" Otherwise an error will come out
    "500":
      COBBLESTONE: 50.0
      STONE: 20.0
      COAL_ORE: 10.0
      IRON_ORE: 10.0
      REDSTONE_ORE: 5.0
      DIAMOND_ORE: 4.0
      EMERALD_ORE: 1.0
